In [26]:
import numpy as np

In [27]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [28]:
d=[]
for i in h:
    d.append(i+5)

In [29]:
d

[35, 25, 10, 13, 14]

In [30]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [31]:
tuple (x**2 for x in s)

(36, 4, 9, 81, 49, 25, 64)

In [32]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
s=tuple(k)
s

(36, 4, 9, 81, 49, 25, 64)

In [33]:
m=[]
for i in s:
    if i>30:
        m.append(i)

In [34]:
m

[36, 81, 49, 64]

In [35]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [36]:
arr+5

array([ 25,  55,  35,  75,  85,  45,  41,  59,  28, 103])

In [37]:
arr**2

array([ 400, 2500,  900, 4900, 6400, 1600, 1296, 2916,  529, 9604])

In [38]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [41]:
arr[arr>50]

array([70, 80, 54, 98])

In [42]:
arr[arr<20]

array([], dtype=int32)

In [43]:
np.where(arr>50)

(array([3, 4, 7, 9], dtype=int64),)