In [1]:
import numpy as np

In [4]:
a = np.random.randint(30,99,(7,8))
a

array([[68, 64, 62, 43, 51, 47, 95, 53],
       [91, 80, 71, 58, 48, 46, 79, 91],
       [87, 45, 94, 43, 56, 74, 35, 35],
       [74, 95, 85, 43, 74, 46, 51, 55],
       [66, 96, 33, 43, 58, 33, 82, 74],
       [78, 89, 91, 38, 30, 70, 81, 40],
       [85, 91, 59, 36, 94, 61, 56, 77]])

In [6]:
np.random.seed(55)
a = np.random.randint(30,99,20)
a

array([56, 69, 59, 91, 85, 67, 63, 84, 65, 76, 91, 42, 54, 61, 81, 30, 85,
       92, 73, 79])

In [7]:
a[-1]

79

In [8]:
a[4]

85

In [9]:
a.ndim

1

In [11]:
a[19]

79

In [17]:
b=np.random.randint(20,80,(8,9))
b

array([[49, 20, 68, 62, 30, 67, 78, 77, 24],
       [46, 34, 26, 45, 26, 57, 71, 25, 69],
       [49, 43, 25, 63, 45, 55, 58, 70, 38],
       [58, 65, 52, 49, 76, 34, 37, 27, 38],
       [50, 61, 53, 68, 45, 21, 63, 30, 75],
       [69, 70, 33, 71, 79, 72, 22, 43, 44],
       [56, 55, 50, 70, 33, 34, 56, 24, 58],
       [31, 26, 68, 38, 39, 30, 78, 46, 56]])

In [15]:
b.shape

(8, 9)

In [16]:
b.ndim

2

In [18]:
b[0]

array([49, 20, 68, 62, 30, 67, 78, 77, 24])

In [20]:
b[7,0]

31

In [23]:
b[2:6:1,1:7:2]

array([[43, 63, 55],
       [65, 49, 34],
       [61, 68, 21],
       [70, 71, 72]])

In [24]:
import pandas as pd

In [27]:
k=[4,7,2,9,7,3,90,50]
k

[4, 7, 2, 9, 7, 3, 90, 50]

In [28]:
np.array(k)

array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [29]:
pd.Series(k)

0     4
1     7
2     2
3     9
4     7
5     3
6    90
7    50
dtype: int64

In [30]:
pd.DataFrame(k)

0
0   4
1   7
2   2
3   9
4   7
5   3
6  90
7  50

In [32]:
q=[[4,7],[2,9],[7,3],[90,50]]
q

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [34]:
t=np.array(q)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [35]:
t.ndim

2

In [37]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [44]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [47]:
df=pd.DataFrame(t,columns=['name','sub'],index=[1,2,3,4])
df

name  sub
1     4    7
2     2    9
3     7    3
4    90   50

In [48]:
df.columns

Index(['name', 'sub'], dtype='object')

In [52]:
df['name']

1     4
2     2
3     7
4    90
Name: name, dtype: int32

In [51]:
df['name'].mean()

25.75

In [53]:
df['name'].mode()

0     2
1     4
2     7
3    90
Name: name, dtype: int32

In [54]:
df['name'].median()

5.5

In [55]:
df['name'].std()

42.88259165053655

In [57]:
df['name'].min()

2

In [59]:
df['name'].max()

90

In [60]:
df['name'].quantile(0.25)

3.5

In [50]:
df.sub

<bound method DataFrame.sub of    name  sub
1     4    7
2     2    9
3     7    3
4    90   50>